### ISSUE TITLE
Add this extension to the official list

### ISSUE THREAD

**Issue by lapineige** [Korbak/freshrss-invidious#1]
Thanks a lot for this tool :rocket:

This great extension is worth adding in the official list https://github.com/FreshRSS/Extensions :slightly_smiling_face: :wink:

**Comment by Korbak** [comment]
Thanks !
I... tried. I don't know how the heck to do this correctly.

**Comment by lapineige** [comment]
Ok I just saw that you did it there: https://github.com/FreshRSS/Extensions/pull/57
